<?php

return [
    'modules' => [
        'users' => [
            'key' => 'users',
            'label' => 'İstifadəçilər',
            'description' => 'Hesabların yaradılması və idarə olunması',
            'roles' => ['regionoperator', 'sektoradmin', 'schooladmin', 'müəllim'],
            'defaults' => ['users.read'],
            'required' => ['users.read'],
            'dependencies' => [
                'users.update' => ['users.read'],
                'users.delete' => ['users.read', 'users.update'],
            ],
            'permissions' => [
                ['key' => 'users.read', 'label' => 'İstifadəçiləri gör', 'description' => 'İstifadəçi siyahısına baxmaq'],
                ['key' => 'users.create', 'label' => 'İstifadəçi yarat', 'description' => 'Yeni istifadəçi əlavə etmək'],
                ['key' => 'users.update', 'label' => 'İstifadəçi redaktə et', 'description' => 'Mövcud hesabı dəyişmək'],
                ['key' => 'users.delete', 'label' => 'İstifadəçi sil', 'description' => 'Hesabı deaktiv etmək və ya silmək'],
            ],
        ],
        'teachers' => [
            'key' => 'teachers',
            'label' => 'Müəllimlər',
            'description' => 'Müəllim profillərinin idarə edilməsi',
            'roles' => ['regionoperator', 'sektoradmin', 'schooladmin'],
            'defaults' => ['teachers.read'],
            'dependencies' => [
                'teachers.create' => ['teachers.read'],
                'teachers.update' => ['teachers.read'],
                'teachers.delete' => ['teachers.read'],
            ],
            'permissions' => [
                ['key' => 'teachers.read', 'label' => 'Müəllimləri gör', 'description' => 'Müəllim siyahısını görüntüləmək'],
                ['key' => 'teachers.create', 'label' => 'Müəllim yarat', 'description' => 'Yeni müəllim profili yaratmaq'],
                ['key' => 'teachers.update', 'label' => 'Müəllim redaktə et', 'description' => 'Mövcud müəllim məlumatlarını dəyişmək'],
                ['key' => 'teachers.delete', 'label' => 'Müəllim sil', 'description' => 'Müəllim hesabını silmək'],
                ['key' => 'teachers.analytics', 'label' => 'Analitika', 'description' => 'Müəllim performans göstəricilərini görmək'],
            ],
        ],
        'surveys' => [
            'key' => 'surveys',
            'label' => 'Sorğular',
            'description' => 'Sorğu yaradılması və dərc olunması',
            'roles' => ['regionoperator', 'sektoradmin', 'schooladmin'],
            'defaults' => ['surveys.read'],
            'dependencies' => [
                'surveys.create' => ['surveys.read'],
                'surveys.update' => ['surveys.read'],
                'surveys.delete' => ['surveys.read'],
                'surveys.publish' => ['surveys.read', 'surveys.create'],
            ],
            'permissions' => [
                ['key' => 'surveys.read', 'label' => 'Sorğuları gör', 'description' => 'Sorğu siyahısını oxumaq'],
                ['key' => 'surveys.create', 'label' => 'Sorğu yarat', 'description' => 'Yeni sorğu hazırlamaq'],
                ['key' => 'surveys.update', 'label' => 'Sorğu redaktə et', 'description' => 'Sorğu məzmununu dəyişmək'],
                ['key' => 'surveys.delete', 'label' => 'Sorğu sil', 'description' => 'Sorğunu sistemdən silmək'],
                ['key' => 'surveys.publish', 'label' => 'Sorğunu dərc et', 'description' => 'Sorğunu məktəblərə göndərmək'],
            ],
        ],
        'survey_responses' => [
            'key' => 'survey_responses',
            'label' => 'Sorğu Cavabları',
            'description' => 'Sorğu cavablarını təsdiqləmə və idarəetmə',
            'roles' => ['regionoperator', 'sektoradmin', 'schooladmin'],
            'defaults' => ['survey_responses.read'],
            'dependencies' => [
                'survey_responses.write' => ['survey_responses.read'],
                'survey_responses.approve' => ['survey_responses.read'],
                'survey_responses.bulk_approve' => ['survey_responses.read'],
            ],
            'permissions' => [
                ['key' => 'survey_responses.read', 'label' => 'Cavabları gör', 'description' => 'Cavab siyahısını oxumaq'],
                ['key' => 'survey_responses.write', 'label' => 'Cavabları idarə et', 'description' => 'Cavablara düzəliş etmək'],
                ['key' => 'survey_responses.approve', 'label' => 'Cavab təsdiqlə', 'description' => 'Sorğu cavablarını təsdiqləmək'],
                ['key' => 'survey_responses.bulk_approve', 'label' => 'Toplu təsdiqlə', 'description' => 'Çoxsaylı cavabları eyni anda təsdiqləmək'],
            ],
        ],
        'tasks' => [
            'key' => 'tasks',
            'label' => 'Tapşırıqlar',
            'description' => 'Tapşırıq təyin etmə və izləmə',
            'roles' => ['regionoperator', 'sektoradmin', 'schooladmin'],
            'defaults' => ['tasks.read'],
            'dependencies' => [
                'tasks.create' => ['tasks.read'],
                'tasks.update' => ['tasks.read'],
                'tasks.delete' => ['tasks.read'],
                'tasks.approve' => ['tasks.read'],
            ],
            'permissions' => [
                ['key' => 'tasks.read', 'label' => 'Tapşırıqları gör', 'description' => 'Tapşırıq siyahısını izləmək'],
                ['key' => 'tasks.create', 'label' => 'Tapşırıq yarat', 'description' => 'Yeni tapşırıq qeyd etmək'],
                ['key' => 'tasks.update', 'label' => 'Tapşırıq redaktə et', 'description' => 'Tapşırıq məlumatlarını dəyişmək'],
                ['key' => 'tasks.delete', 'label' => 'Tapşırıq sil', 'description' => 'Tapşırığı ləğv etmək'],
                ['key' => 'tasks.approve', 'label' => 'Tapşırıq təsdiqlə', 'description' => 'Tapşırıq icrasını təsdiqləmək'],
            ],
        ],
        'documents' => [
            'key' => 'documents',
            'label' => 'Sənədlər',
            'description' => 'Sənəd kitabxanasının idarə olunması',
            'roles' => ['regionoperator', 'sektoradmin', 'schooladmin', 'müəllim'],
            'defaults' => ['documents.read'],
            'dependencies' => [
                'documents.create' => ['documents.read'],
                'documents.update' => ['documents.read'],
                'documents.delete' => ['documents.read'],
                'documents.share' => ['documents.read'],
            ],
            'permissions' => [
                ['key' => 'documents.read', 'label' => 'Sənədləri gör', 'description' => 'Kitabxananı görüntüləmək'],
                ['key' => 'documents.create', 'label' => 'Sənəd yüklə', 'description' => 'Yeni sənəd əlavə etmək'],
                ['key' => 'documents.update', 'label' => 'Sənəd redaktə et', 'description' => 'Sənəd məlumatlarını dəyişmək'],
                ['key' => 'documents.delete', 'label' => 'Sənəd sil', 'description' => 'Sənədi sistemdən silmək'],
                ['key' => 'documents.share', 'label' => 'Sənədi paylaş', 'description' => 'Sənədi digər təşkilatlarla paylaşmaq'],
            ],
        ],
        'links' => [
            'key' => 'links',
            'label' => 'Bağlantılar',
            'description' => 'Faydalı linklərin paylaşılıb izlənməsi',
            'roles' => ['regionoperator', 'sektoradmin', 'schooladmin', 'müəllim'],
            'defaults' => ['links.read'],
            'dependencies' => [
                'links.create' => ['links.read'],
                'links.update' => ['links.read'],
                'links.delete' => ['links.read'],
                'links.share' => ['links.read'],
            ],
            'permissions' => [
                ['key' => 'links.read', 'label' => 'Linkləri gör', 'description' => 'Link kataloqunu oxumaq'],
                ['key' => 'links.create', 'label' => 'Link əlavə et', 'description' => 'Yeni link paylaşmaq'],
                ['key' => 'links.update', 'label' => 'Link redaktə et', 'description' => 'Link məlumatlarını dəyişmək'],
                ['key' => 'links.delete', 'label' => 'Link sil', 'description' => 'Linki sistemdən silmək'],
                ['key' => 'links.share', 'label' => 'Link paylaş', 'description' => 'Linkləri institutlarla bölüşmək'],
            ],
        ],
        'approvals' => [
            'key' => 'approvals',
            'label' => 'Təsdiqlər',
            'description' => 'Müraciət və təsdiq axınları',
            'roles' => ['regionoperator', 'sektoradmin'],
            'defaults' => ['approvals.read'],
            'dependencies' => [
                'approvals.create' => ['approvals.read'],
                'approvals.approve' => ['approvals.read'],
                'approvals.reject' => ['approvals.read'],
            ],
            'permissions' => [
                ['key' => 'approvals.read', 'label' => 'Təsdiq axınını gör', 'description' => 'Müraciətləri izləmək'],
                ['key' => 'approvals.create', 'label' => 'Təsdiq yarat', 'description' => 'Yeni təsdiq prosesi başlatmaq'],
                ['key' => 'approvals.approve', 'label' => 'Təsdiqlə', 'description' => 'Müraciəti təsdiqləmək'],
                ['key' => 'approvals.reject', 'label' => 'Rədd et', 'description' => 'Müraciəti rədd etmək'],
                ['key' => 'approvals.delegate', 'label' => 'Delegasiya et', 'description' => 'Təsdiqi digər istifadəçiyə yönləndirmək'],
            ],
        ],
        'classes' => [
            'key' => 'classes',
            'label' => 'Siniflər',
            'description' => 'Siniflərin idarə olunması',
            'roles' => ['regionoperator', 'sektoradmin', 'schooladmin'],
            'defaults' => ['classes.read'],
            'dependencies' => [
                'classes.create' => ['classes.read'],
                'classes.update' => ['classes.read'],
                'classes.delete' => ['classes.read'],
                'classes.manage' => ['classes.read'],
                'classes.assign' => ['classes.read'],
                'classes.schedule' => ['classes.read'],
                'classes.teachers' => ['classes.read'],
                'classes.students' => ['classes.read'],
            ],
            'permissions' => [
                ['key' => 'classes.read', 'label' => 'Sinifləri gör', 'description' => 'Sinif siyahılarına baxmaq'],
                ['key' => 'classes.create', 'label' => 'Sinif yarat', 'description' => 'Yeni sinif əlavə etmək'],
                ['key' => 'classes.update', 'label' => 'Sinif redaktə et', 'description' => 'Sinif məlumatlarını dəyişmək'],
                ['key' => 'classes.delete', 'label' => 'Sinif sil', 'description' => 'Sinifi sistemdən silmək'],
                ['key' => 'classes.manage', 'label' => 'Sinifləri idarə et', 'description' => 'Sinif parametrlərinə nəzarət'],
                ['key' => 'classes.assign', 'label' => 'Sinif təyin et', 'description' => 'Sinifləri müəssisələrə və ya müəllimlərə təyin etmək'],
                ['key' => 'classes.teachers', 'label' => 'Müəllim təyinatı', 'description' => 'Sinif-müəllim əlaqələrini idarə etmək'],
                ['key' => 'classes.students', 'label' => 'Şagird təyinatı', 'description' => 'Sinif-şagird əlaqələrini idarə etmək'],
                ['key' => 'classes.attendance', 'label' => 'Sinif davamiyyəti', 'description' => 'Sinif səviyyəsində davamiyyətə baxmaq'],
                ['key' => 'classes.schedule', 'label' => 'Sinif cədvəli', 'description' => 'Siniflərin dərs cədvəllərini idarə etmək'],
                ['key' => 'classes.analytics', 'label' => 'Sinif analitikası', 'description' => 'Sinif göstəricilərini izləmək'],
            ],
        ],
        'institutions' => [
            'key' => 'institutions',
            'label' => 'Müəssisələr',
            'description' => 'Müəssisə idarəsi',
            'roles' => ['regionoperator', 'sektoradmin', 'schooladmin'],
            'defaults' => ['institutions.read'],
            'dependencies' => [
                'institutions.create' => ['institutions.read'],
                'institutions.update' => ['institutions.read'],
                'institutions.delete' => ['institutions.read'],
                'institutions.write' => ['institutions.read'],
            ],
            'permissions' => [
                ['key' => 'institutions.read', 'label' => 'Müəssisələri gör', 'description' => 'Müəssisə siyahısını görüntüləmək'],
                ['key' => 'institutions.create', 'label' => 'Müəssisə yarat', 'description' => 'Yeni müəssisə əlavə etmək'],
                ['key' => 'institutions.update', 'label' => 'Müəssisə redaktə et', 'description' => 'Mövcud müəssisə məlumatlarını dəyişmək'],
                ['key' => 'institutions.delete', 'label' => 'Müəssisə sil', 'description' => 'Müəssisəni sistemdən silmək'],
                ['key' => 'institutions.write', 'label' => 'Müəssisə yazma əməliyyatları', 'description' => 'Müəssisə üzərində yazma əməliyyatlarına icazə'],
                ['key' => 'institutions.hierarchy', 'label' => 'Müəssisə iyerarxiyası', 'description' => 'Regional iyerarxiya strukturuna baxmaq'],
            ],
        ],
        'attendance' => [
            'key' => 'attendance',
            'label' => 'Davamiyyət',
            'description' => 'Davamiyyət qeydiyyatı və hesabatları',
            'roles' => ['regionoperator', 'sektoradmin', 'schooladmin'],
            'defaults' => ['attendance.read'],
            'dependencies' => [
                'attendance.create' => ['attendance.read'],
                'attendance.update' => ['attendance.read'],
                'attendance.delete' => ['attendance.read'],
            ],
            'permissions' => [
                ['key' => 'attendance.read', 'label' => 'Davamiyyəti gör', 'description' => 'Davamiyyət hesabatlarını oxumaq'],
                ['key' => 'attendance.create', 'label' => 'Davamiyyət əlavə et', 'description' => 'Yeni davamiyyət qeydi daxil etmək'],
                ['key' => 'attendance.update', 'label' => 'Davamiyyəti redaktə et', 'description' => 'Mövcud davamiyyət qeydlərini dəyişmək'],
                ['key' => 'attendance.delete', 'label' => 'Davamiyyət sil', 'description' => 'Davamiyyət qeydlərini silmək'],
                ['key' => 'attendance.manage', 'label' => 'Davamiyyət idarəsi', 'description' => 'Regional davamiyyət siyasətini idarə etmək'],
                ['key' => 'students.attendance', 'label' => 'Şagird davamiyyətinə bax', 'description' => 'Şagird səviyyəsində davamiyyət hesabatları'],
            ],
        ],
        'assessments' => [
            'key' => 'assessments',
            'label' => 'Qiymətləndirmə',
            'description' => 'Qiymətləndirmə və test prosesləri',
            'roles' => ['regionoperator', 'sektoradmin', 'schooladmin'],
            'defaults' => ['assessments.read'],
            'dependencies' => [
                'assessments.create' => ['assessments.read'],
                'assessments.update' => ['assessments.read'],
                'assessments.delete' => ['assessments.read'],
                'assessments.approve' => ['assessments.read'],
            ],
            'permissions' => [
                ['key' => 'assessments.read', 'label' => 'Qiymətləndirmələri gör', 'description' => 'Qiymətləndirmə siyahılarını oxumaq'],
                ['key' => 'assessments.create', 'label' => 'Qiymətləndirmə yarat', 'description' => 'Yeni qiymətləndirmə əlavə etmək'],
                ['key' => 'assessments.update', 'label' => 'Qiymətləndirmə redaktə et', 'description' => 'Qiymətləndirmə məlumatlarını dəyişmək'],
                ['key' => 'assessments.delete', 'label' => 'Qiymətləndirmə sil', 'description' => 'Qiymətləndirməni sistemdən silmək'],
                ['key' => 'assessments.approve', 'label' => 'Qiymətləndirmə təsdiqlə', 'description' => 'Qiymətləndirmələri təsdiqləmək'],
                ['key' => 'assessments.export', 'label' => 'Qiymətləndirmə ixracı', 'description' => 'Qiymətləndirmə nəticələrini ixrac etmək'],
                ['key' => 'assessment-types.read', 'label' => 'Növəri gör', 'description' => 'Qiymətləndirmə növlərini oxumaq'],
                ['key' => 'assessment-types.manage', 'label' => 'Növ idarə et', 'description' => 'Qiymətləndirmə növlərini idarə etmək'],
            ],
        ],
        'schedules' => [
            'key' => 'schedules',
            'label' => 'Regional Cədvəl',
            'description' => 'Regional dərs cədvəlləri',
            'roles' => ['regionoperator', 'sektoradmin', 'schooladmin'],
            'defaults' => ['schedules.read'],
            'dependencies' => [
                'schedules.create' => ['schedules.read'],
                'schedules.update' => ['schedules.read'],
                'schedules.delete' => ['schedules.read'],
                'schedules.approve' => ['schedules.read'],
            ],
            'permissions' => [
                ['key' => 'schedules.read', 'label' => 'Cədvəlləri gör', 'description' => 'Regional cədvəl panelini oxumaq'],
                ['key' => 'schedules.create', 'label' => 'Cədvəl yarat', 'description' => 'Yeni cədvəl əlavə etmək'],
                ['key' => 'schedules.update', 'label' => 'Cədvəl redaktə et', 'description' => 'Cədvəl məlumatlarını dəyişmək'],
                ['key' => 'schedules.delete', 'label' => 'Cədvəl sil', 'description' => 'Cədvəli silmək'],
                ['key' => 'schedules.approve', 'label' => 'Cədvəl təsdiqlə', 'description' => 'Cədvəlləri təsdiqləmək'],
            ],
        ],
        'teacher_performance' => [
            'key' => 'teacher_performance',
            'label' => 'Müəllim performansı',
            'description' => 'Müəllim performansını izləmə',
            'roles' => ['regionoperator', 'sektoradmin'],
            'defaults' => ['view teacher_performance'],
            'dependencies' => [
                'create teacher_performance' => ['view teacher_performance'],
                'edit teacher_performance' => ['view teacher_performance'],
                'manage teacher_performance' => ['view teacher_performance'],
                'approve teacher_performance' => ['view teacher_performance'],
            ],
            'permissions' => [
                ['key' => 'view teacher_performance', 'label' => 'Performansı gör', 'description' => 'Müəllim performansını izləmək'],
                ['key' => 'create teacher_performance', 'label' => 'Performans yaradır', 'description' => 'Yeni performans qeydi əlavə etmək'],
                ['key' => 'edit teacher_performance', 'label' => 'Performansı redaktə et', 'description' => 'Performans qeydlərini dəyişmək'],
                ['key' => 'manage teacher_performance', 'label' => 'Performansı idarə et', 'description' => 'Performans idarəetməsi'],
                ['key' => 'approve teacher_performance', 'label' => 'Performansı təsdiqlə', 'description' => 'Performans qeydlərini təsdiqləmək'],
            ],
        ],
    ],
    'templates' => [
        'user_manager' => [
            'key' => 'user_manager',
            'label' => 'İstifadəçi meneceri',
            'description' => 'İstifadəçi və müəllim idarəçiliyi üçün əsas paket',
            'permissions' => ['users.read', 'users.create', 'users.update', 'teachers.read', 'teachers.update'],
        ],
        'survey_coordinator' => [
            'key' => 'survey_coordinator',
            'label' => 'Sorğu koordinatoru',
            'description' => 'Sorğu yaradıb dərc edən rol',
            'permissions' => ['surveys.read', 'surveys.create', 'surveys.update', 'surveys.publish', 'survey_responses.read'],
        ],
        'task_supervisor' => [
            'key' => 'task_supervisor',
            'label' => 'Tapşırıq nəzarətçisi',
            'description' => 'Tapşırıqların yaradılması və monitorinqi',
            'permissions' => ['tasks.read', 'tasks.create', 'tasks.update', 'tasks.approve'],
        ],
        'document_curator' => [
            'key' => 'document_curator',
            'label' => 'Sənəd kuratoru',
            'description' => 'Sənəd və link bölmələrinə nəzarət',
            'permissions' => ['documents.read', 'documents.create', 'documents.update', 'documents.share', 'links.read', 'links.create', 'links.share'],
        ],
        'class_manager' => [
            'key' => 'class_manager',
            'label' => 'Sinif meneceri',
            'description' => 'Sinif, müəllim və şagird idarəetməsi',
            'permissions' => ['classes.read', 'classes.create', 'classes.update', 'classes.teachers', 'classes.students', 'teachers.read', 'students.attendance'],
        ],
        'attendance_supervisor' => [
            'key' => 'attendance_supervisor',
            'label' => 'Davamiyyət nəzarətçisi',
            'description' => 'Davamiyyət hesabatı və idarəsi',
            'permissions' => ['attendance.read', 'attendance.manage', 'students.attendance'],
        ],
        'assessment_lead' => [
            'key' => 'assessment_lead',
            'label' => 'Qiymətləndirmə rəhbəri',
            'description' => 'Qiymətləndirmə və növlərini idarə et',
            'permissions' => ['assessments.read', 'assessments.create', 'assessments.update', 'assessments.approve', 'assessment-types.manage'],
        ],
        'schedule_controller' => [
            'key' => 'schedule_controller',
            'label' => 'Cədvəl nəzarətçisi',
            'description' => 'Regional cədvəl hazırlamaq və təsdiqləmək',
            'permissions' => ['schedules.read', 'schedules.create', 'schedules.update', 'schedules.approve', 'classes.schedule'],
        ],
    ],
];
