version: '3.8'

services:
  # Frontend (Vite Development Server)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_BASE_URL=http://localhost:8000/api
      - VITE_API_URL=http://localhost:8000/api
      - VITE_APP_NAME=ATİS
      - VITE_APP_ENV=development
      - VITE_ENABLE_DEBUG_PANEL=true
    command: npm run dev -- --host 0.0.0.0 --port 3000
    depends_on:
      - backend
    networks:
      - atis-network

  # Backend (Laravel Development Server)  
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www/html
      - /var/www/html/vendor
      - /var/www/html/node_modules
    environment:
      - APP_NAME=ATIS
      - APP_ENV=local
      - APP_KEY=base64:your-app-key-here
      - APP_DEBUG=true
      - APP_URL=http://localhost:8000
      - DB_CONNECTION=pgsql
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=atis_local
      - DB_USERNAME=atis_user
      - DB_PASSWORD=atis_password
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CACHE_DRIVER=redis
      - SESSION_DRIVER=redis
      - QUEUE_CONNECTION=redis
    command: php artisan serve --host=0.0.0.0 --port=8000
    depends_on:
      - postgres
      - redis
    networks:
      - atis-network

  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: atis_local
      POSTGRES_USER: atis_user
      POSTGRES_PASSWORD: atis_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - atis-network

  # Redis Cache & Session Store
  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - atis-network

  # Nginx (Optional - for production-like setup)
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/local.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - atis-network

  # pgAdmin for database management
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@atis.local
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - atis-network

  # MailCatcher for email testing
  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"  # Web interface
      - "1025:1025"  # SMTP server
    networks:
      - atis-network

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  atis-network:
    driver: bridge