import {
  LayoutDashboard,
  Users,
  Shield,
  FileText,
  MapPin,
  Building2,
  School,
  BarChart3,
  CheckSquare,
  BookOpen,
  Bell,
  Database,
  Monitor,
  Settings,
  Clipboard,
  Baby,
  GraduationCap,
  UserCheck,
  Target,
  Calendar,
  Folder,
  User,
  Sparkles,
  Bot,
  ClipboardCheck,
  ExternalLink,
  Wrench,
} from 'lucide-react';
import { USER_ROLES } from '@/constants/roles';
import {
  REGION_ADMIN_ROLES,
  REGION_ROLES,
  REGION_AND_ABOVE,
  SCHOOL_ADMIN_ROLES,
  MGMT_ROLES,
  REPORTING_ROLES,
  ALL_ADMINS,
} from './roleSets';
import { MenuGroup } from './types';

export const managementMenuGroups: MenuGroup[] = [
  // ─── Sistem İdarəetməsi ───────────────────────────────────────────────────
  {
    id: 'system-structure',
    label: 'Sistem İdarəetməsi',
    panel: 'management',
    roles: REGION_AND_ABOVE,
    items: [
      {
        id: 'users',
        label: 'İstifadəçilər',
        path: '/users',
        icon: Users,
        roles: MGMT_ROLES,
      },
      {
        id: 'roles',
        label: 'Rollar',
        path: '/roles',
        icon: Shield,
        roles: [USER_ROLES.SUPERADMIN],
      },
      {
        id: 'permissions',
        label: 'Səlahiyyətlər',
        path: '/permissions',
        icon: CheckSquare,
        roles: [USER_ROLES.SUPERADMIN],
        description: 'Sistem səlahiyyətlərinin idarə edilməsi',
      },
      {
        id: 'departments',
        label: 'Departmentlər',
        path: '/departments',
        icon: Building2,
        roles: MGMT_ROLES,
      },
      {
        id: 'region-teachers',
        label: 'Müəllimlər',
        path: '/regionadmin/teachers',
        icon: GraduationCap,
        roles: REGION_AND_ABOVE,
      },
      {
        id: 'region-classes',
        label: 'Siniflər',
        path: '/regionadmin/classes',
        icon: Users,
        roles: REGION_AND_ABOVE,
      },
      {
        id: 'region-students',
        label: 'Şagirdlər',
        path: '/regionadmin/students',
        icon: GraduationCap,
        roles: REGION_AND_ABOVE,
      },
      {
        id: 'regions',
        label: 'Regionlar',
        path: '/regions',
        icon: MapPin,
        roles: [USER_ROLES.SUPERADMIN],
      },
      {
        id: 'sectors',
        label: 'Sektorlar',
        path: '/sectors',
        icon: Target,
        roles: REGION_AND_ABOVE,
      },
      {
        id: 'institutions',
        label: 'Ümumi Təhsil',
        path: '/institutions',
        icon: School,
        roles: REGION_AND_ABOVE,
      },
      {
        id: 'preschools',
        label: 'Məktəbəqədər',
        path: '/preschools',
        icon: Baby,
        roles: [
          USER_ROLES.SUPERADMIN,
          USER_ROLES.REGIONADMIN,
          USER_ROLES.REGIONOPERATOR,
          USER_ROLES.PRESCHOOLADMIN,
        ],
      },
      {
        id: 'hierarchy',
        label: 'İerarxiya İdarəsi',
        path: '/hierarchy',
        icon: Database,
        roles: REGION_ADMIN_ROLES,
      },
      {
        id: 'subjects',
        label: 'Fənnlər',
        path: '/subjects',
        icon: BookOpen,
        roles: REGION_ADMIN_ROLES,
      },
      {
        id: 'academic-year-management',
        label: 'Təhsil İlləri',
        path: '/academic-year-management',
        icon: Calendar,
        roles: [USER_ROLES.SUPERADMIN],
        description: 'Təhsil illərinin idarə edilməsi və tənzimlənməsi',
      },
    ],
  },

  // ─── Məktəb İdarəsi ───────────────────────────────────────────────────────
  {
    id: 'school-management',
    label: 'Məktəb İdarəsi',
    panel: 'management',
    roles: [USER_ROLES.SUPERADMIN, USER_ROLES.SCHOOLADMIN, USER_ROLES.MUELLIM],
    items: [
      {
        id: 'my-classes',
        label: 'Mənim Siniflərim',
        path: '/teacher/classes',
        icon: School,
        roles: [USER_ROLES.MUELLIM],
        description: 'Müəllimin təyin edildiyi siniflər',
      },
      {
        id: 'students',
        label: 'Şagirdlər',
        path: '/students',
        icon: Users,
        roles: SCHOOL_ADMIN_ROLES,
      },
      {
        id: 'school-teachers',
        label: 'Müəllimlər',
        path: '/school/teachers',
        icon: GraduationCap,
        roles: SCHOOL_ADMIN_ROLES,
      },
      {
        id: 'school-classes',
        label: 'Siniflər',
        path: '/school/classes',
        icon: Building2,
        roles: SCHOOL_ADMIN_ROLES,
      },
      {
        id: 'preschool-groups',
        label: 'Qruplar (MB)',
        path: '/preschool/groups',
        icon: Baby,
        description: 'Məktəbəqədər qrupların idarəsi',
        roles: SCHOOL_ADMIN_ROLES,
        permissions: ['preschool.groups.manage'],
        permissionMatch: 'any',
      },
      {
        id: 'preschool-attendance-entry',
        label: 'MB Davamiyyəti',
        path: '/preschool/attendance',
        icon: ClipboardCheck,
        description: 'Məktəbəqədər davamiyyət qeydiyyatı',
        roles: SCHOOL_ADMIN_ROLES,
        permissions: ['preschool.attendance.write'],
        permissionMatch: 'any',
      },
    ],
  },

  // ─── Hesabat və Analitika ─────────────────────────────────────────────────
  {
    id: 'analytics',
    label: 'Hesabat və Analitika',
    panel: 'management',
    roles: REPORTING_ROLES,
    items: [
      {
        id: 'reports',
        label: 'Hesabatlar',
        path: '/reports',
        icon: FileText,
        roles: REGION_AND_ABOVE,
        permissions: ['reports.read'],
      },
      {
        id: 'sector-attendance-reports',
        label: 'Davamiyyət Hesabatları',
        path: '/school/attendance?tab=reports',
        icon: FileText,
        roles: [USER_ROLES.SEKTORADMIN],
      },
      {
        id: 'sector-assessment-reports',
        label: 'Qiymətləndirmə Hesabatları',
        path: '/assessments/results',
        icon: FileText,
        roles: [USER_ROLES.SEKTORADMIN],
      },
      {
        id: 'system-analytics',
        label: 'Sistem Analitikası',
        path: '/analytics',
        icon: BarChart3,
        roles: [
          USER_ROLES.SUPERADMIN,
          USER_ROLES.REGIONADMIN,
          USER_ROLES.SEKTORADMIN,
          USER_ROLES.SCHOOLADMIN,
          USER_ROLES.REGIONOPERATOR,
        ],
        permissions: ['analytics.view'],
      },
      {
        id: 'preschool-attendance-reports',
        label: 'MB Davamiyyət Hesabatı',
        path: '/preschool/attendance/reports',
        icon: BarChart3,
        description: 'Məktəbəqədər davamiyyət hesabatları',
        roles: [
          USER_ROLES.SUPERADMIN,
          USER_ROLES.REGIONADMIN,
          USER_ROLES.REGIONOPERATOR,
          USER_ROLES.SEKTORADMIN,
        ],
        permissions: ['preschool.attendance.reports'],
        permissionMatch: 'any',
      },
      {
        id: 'ai-analysis',
        label: 'AI Analiz',
        path: '/ai-analysis',
        icon: Sparkles,
        description: 'Təbii dillə verilənlər bazası analizi',
        roles: REGION_ADMIN_ROLES,
        permissions: ['ai_analysis.view'],
      },
      {
        id: 'ai-settings',
        label: 'AI İdarəetmə',
        path: '/ai-settings',
        icon: Bot,
        description: 'AI provayder və model konfiqurasiyası',
        roles: [USER_ROLES.SUPERADMIN],
        permissions: ['ai_analysis.view'],
      },
    ],
  },

  // ─── Bildirişlər ──────────────────────────────────────────────────────────
  {
    id: 'notifications',
    label: 'Bildirişlər',
    panel: 'management',
    roles: REPORTING_ROLES,
    items: [
      {
        id: 'notifications-list',
        label: 'Bildirişlər',
        path: '/notifications',
        icon: Bell,
        roles: REPORTING_ROLES,
      },
    ],
  },

  // ─── Hesab ────────────────────────────────────────────────────────────────
  {
    id: 'account',
    label: 'Hesab',
    panel: 'management',
    items: [
      {
        id: 'profile',
        label: 'Profilim',
        path: '/profile',
        icon: User,
      },
    ],
  },

  // ─── Sistem Tənzimləmələri ────────────────────────────────────────────────
  {
    id: 'system-settings',
    label: 'Sistem Tənzimləmələri',
    panel: 'management',
    roles: [USER_ROLES.SUPERADMIN],
    items: [
      {
        id: 'settings',
        label: 'Sistem Parametrləri',
        path: '/settings',
        icon: Settings,
        roles: [USER_ROLES.SUPERADMIN],
      },
      {
        id: 'audit-logs',
        label: 'Audit Logları',
        path: '/audit-logs',
        icon: Clipboard,
        roles: [USER_ROLES.SUPERADMIN],
      },
      {
        id: 'performance',
        label: 'Performans Monitorinqi',
        path: '/performance',
        icon: Monitor,
        roles: [USER_ROLES.SUPERADMIN],
      },
    ],
  },

  // ─── Alətlər ──────────────────────────────────────────────────────────────
  {
    id: 'tools',
    label: 'Alətlər',
    panel: 'management',
    roles: ALL_ADMINS,
    items: [
      {
        id: 'tools-list',
        label: 'Alətlər',
        path: '/tools',
        icon: Wrench,
        roles: ALL_ADMINS,
      },
    ],
  },
];
